### ISSUE TITLE
Setup-Redesign: Needs Finetune On Recovery

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz-web#747] opened 2024-07-10 19:08 UTC
I did on the v1.11.1rc1 a recovery (not a fresh setup) and on final screen  ran into this:

<img width="421" alt="Bildschirmfoto 2024-07-10 um 20 57 22" src="https://github.com/raspiblitz/raspiblitz-web/assets/2472225/a18804d9-0e91-4bcb-a4e7-32d1860a70a5">

- the green part is not needed
- I needed to set the checkmark to be able to continue - this should not be needed on recovery. Button should just be active.

And then after restart it changed after a spinner to this screen:

<img width="394" alt="Bildschirmfoto 2024-07-10 um 21 00 33" src="https://github.com/raspiblitz/raspiblitz-web/assets/2472225/1e2e7d96-2880-42e7-ae04-b458f28ef047">

Its not an initial synchronization - its just starting up. And if the state is not clear .. is lightning, unlocked (its not it just jumped later to need unlock), still starting or has problems? 

The new screen look really good, but for final release we would need some refinement on the status of the node here I think. Let me know what you need from the RaspiBlitz system side - I made a reminder ticket here: 
https://github.com/raspiblitz/raspiblitz/issues/4644

**Comment by escapedcat** [comment] 2024-07-15 08:53
Do you know what data you get from these calls for each screen?

- `/status`
- `/setup-start-info`

Would be great to be able to mock this to fix these issues.
Started to try to fix things blind in #748

**Comment by rootzoll** [comment] 2024-07-18 13:37
I dont habe the data. Do you mean like recording network calls with Browser-DevTools open or calling the API by hand?

This BTW is the srceen on a normal setup under firefox:
![Bildschirmfoto 2024-07-18 um 15 34 16](https://github.com/user-attachments/assets/6031c935-a454-478b-a60b-2b208d2ffbac)

**Comment by escapedcat** [comment] 2024-07-18 17:16
I'll take care of the layout issues and will try to compare the current state to the previous "pre redesign" state as soon as I find some time.

**Comment by escapedcat** [comment] 2024-07-19 08:24
> This BTW is the srceen on a normal setup under firefox: ![Bildschirmfoto 2024-07-18 um 15 29 45](https://private-user-images.githubusercontent.com/2472225/349980619-18380d57-3418-4a21-a074-0c5da6a33e96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMjMyMzcsIm5iZiI6MTcyMTMyMjkzNywicGF0aCI6Ii8yNDcyMjI1LzM0OTk4MDYxOS0xODM4MGQ1Ny0zNDE4LTRhMjEtYTA3NC0wYzVkYTZhMzNlOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MThUMTcxNTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2IxMzVmMWUxMzgwZjIxNGQ2ZWEzMGFhNTgyYjI4ZmUwYjY0NWNhYjgxZmQ0ZWZkN2NmNDkxNWEwZDVkNThkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GGELTpbnvmVmsQLKCne-ykdSS7T3rCIhFKc1mFmjlFE)

Which Firefox is this? Version/OS/...? Can't reproduce this

**Comment by escapedcat** [comment] 2024-07-19 09:27
> And then after restart it changed after a spinner to this screen:
> <img alt="Bildschirmfoto 2024-07-10 um 21 00 33" width="394" src="https://private-user-images.githubusercontent.com/2472225/347567839-1e2e7d96-2880-42e7-ae04-b458f28ef047.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzc3OTUsIm5iZiI6MTcyMTM3NzQ5NSwicGF0aCI6Ii8yNDcyMjI1LzM0NzU2NzgzOS0xZTJlN2Q5Ni0yODgwLTQyZTctYWUwNC1iNDU4ZjI4ZWYwNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTlUMDgyNDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzdhYjU0YmRhYWIzNjg3NDdlZGVkOTZjY2Q1ZTI4YTdkYmViOGIzNWI4OWM3ZDY1MzllMDljZjRjYWUyM2E1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bKfwyUJaBOLiyMa4gF6pRhP__o16KYb58cA0PMAGIRY">
> 
> Its not an initial synchronization - its just starting up. And if the state is not clear .. is lightning, unlocked (its not it just jumped later to need unlock), still starting or has problems?

According to the code this headline wasn't changed. The lightning-wallet functionality was there as well, only the design was updated. Do we know if this screen was shown after a recovery-restart before the design-relaunch as well or if something else was shown?

**Comment by rootzoll** [comment] 2024-07-21 19:32
> Which Firefox is this? Version/OS/...? Can't reproduce this

FIrefox 128.0 MacOS

> Do we know if this screen was shown after a recovery-restart before the design-relaunch as well or if something else was shown?

I think it was also before like this - its not critical .. we can move this part to v1.11.2 - I opend ticket on raspiblitz repo [#4652](https://github.com/raspiblitz/raspiblitz/issues/4652)

**Comment by escapedcat** [comment] 2024-07-22 09:09
> > Which Firefox is this? Version/OS/...? Can't reproduce this
> FIrefox 128.0 MacOS

Pushed a fix. Screen was optimize for Rick Astley words :P

> > Do we know if this screen was shown after a recovery-restart before the design-relaunch as well or if something else was shown?
> I think it was also before like this - its not critical .. we can move this part to v1.11.2 - I opend ticket on raspiblitz repo [#4652](https://github.com/raspiblitz/raspiblitz/issues/4652)

Alright, then I do not investigate further, ok?

**Comment by rootzoll** [comment] 2024-07-24 12:00
@escapedcat on a recovery final setup screen there is still the checkbox "If i have written down my seed words" (what is not needed on recovery)
![Bildschirmfoto 2024-07-24 um 13 55 08](https://github.com/user-attachments/assets/b92b8ce2-0d3e-487f-9469-98221bc252dc)

**Comment by rootzoll** [comment] 2024-07-24 12:03
@escapedcat Oh and I was not able to click "OK, do final Reboot" button (its deactivated) and it even stays deactivated when I do the checkbox. So that is critical: I am stuck at this page.

**Comment by escapedcat** [comment] 2024-07-24 12:14
Alright, will check

**Comment by rootzoll** [comment] 2024-07-24 13:31
Also similar when setting up a fresh node ... the Button to continue on the final screen (here with a node Bitcoin only - no seed words) stays deactovated independent of the checkbox state. Is this already addressed in the PR #752 ?

**Comment by escapedcat** [comment] 2024-07-24 13:35
> Also similar when setting up a fresh node ... the Button to continue on the final screen (here with a node Bitcoin only - no seed words) stays deactovated independent of the checkbox state. Is this already addressed in the PR #752 ? !

Should be, yes 🤞

**Closed** 2024-07-24 13:34 UTC
Labels: check

**Comment by rootzoll** [comment] 2024-07-24 14:13
> Should be, yes 🤞

Looks good on first tests

**Comment by rootzoll** [comment] 2024-07-24 20:40
OK were good now thx - building an RC3.
